[package]
name = "app"
version = "0.1.0"
description = "Authenticator Example App"
authors = [ "Evan Feenstra <evanfeenstra@gmail.com>" ]
license = ""
repository = ""
edition = "2018"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
tauri = { git = "https://github.com/tauri-apps/tauri", branch = "dev", features =["api-all"]}
tauri-authenticator = { path = "../../../" }

[build-dependencies]
tauri-build = "1.0.0-beta-rc.0"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
